### PR TITLE
Trying to add ElectraMod and XPlab support

### PR DESCRIPTION
**Pull request by Aness6040**

### CODE REVIEW

**Comment by Aness6040** [comment]
@SimonShiki pls add this support (because XPlab and ElectraMod are supported on Eureka but not in Charlotte)

**Comment by Aness6040** [comment]
image

**Review by SimonShiki — APPROVED** [review]

**Comment by Aness6040** [comment]
@SimonShiki Why i don't see my changes on GitHub?

**Comment by Aness6040** [comment]
@SimonShiki I think u merged commit but not pushed

**Pull request merged**
