### PR TITLE
✨ Adding 2 new platforms

### PR DESCRIPTION
**Pull request by Aness6040**
because old one doesnt appear

### CODE REVIEW

**Comment by Aness6040** [comment]
@SimonShiki

**Review by SimonShiki — CHANGES_REQUESTED** [review]
add matcher (match.ts)

**Comment by SimonShiki** [comment]
also, please standardize commit message format and pull request titles

**Comment by Aness6040** [comment]
> also, please standardize commit message format and pull request titles

Okay, I edited PR message

**Comment by Aness6040** [comment]
@SimonShiki Now, can you merge it please? (And update it?)

**Review by SimonShiki — APPROVED** [review]

**Pull request merged**
